DEFINT A-Z
COMMON SHARED Error_Display AS STRING
COMMON SHARED Error_msg AS STRING
COMMON SHARED Ver AS STRING
COMMON SHARED bout AS STRING
COMMON SHARED tout AS STRING
COMMON SHARED BG_Count AS LONG
COMMON SHARED ConnErr
COMMON SHARED Refresh_Request
COMMON SHARED RefreshDisplayRequest
COMMON SHARED rtmp_uptime#
COMMON SHARED ba&
COMMON SHARED winstyle&
COMMON SHARED timerFree
COMMON SHARED BG AS DOUBLE
COMMON SHARED BG_New AS DOUBLE
COMMON SHARED BGA AS DOUBLE
COMMON SHARED __BGA AS _BYTE
COMMON SHARED SpaceLength AS INTEGER
COMMON SHARED ProgressCounter AS INTEGER
COMMON SHARED updateResult AS STRING
COMMON SHARED updateDisplay AS INTEGER
COMMON SHARED updateDisplayCounter AS INTEGER
COMMON SHARED verCheck AS STRING
COMMON SHARED CheckUpdateOnStartup AS STRING
COMMON SHARED file224 AS STRING
COMMON SHARED __FileStatusOutput AS _BYTE
COMMON SHARED FileStatusOutput AS STRING
COMMON SHARED outputStatusFile AS STRING
COMMON SHARED iniFeatures AS _BYTE
COMMON SHARED Debug AS _BYTE
COMMON SHARED q
COMMON SHARED Timer_Failed AS _BYTE
COMMON SHARED WebsocketMethod AS STRING
COMMON SHARED c34 AS STRING

COMMON SHARED image_data() AS _UNSIGNED LONG
COMMON SHARED Scene_OK AS STRING
COMMON SHARED Scene_Fail AS STRING
COMMON SHARED Scene_Intro AS STRING
COMMON SHARED URL AS STRING
COMMON SHARED Port AS STRING
COMMON SHARED OBS_URL AS STRING
COMMON SHARED OBS_PW AS STRING
COMMON SHARED urlStream1 AS STRING
COMMON SHARED urlStream2 AS STRING
COMMON SHARED titleScene1 AS STRING
COMMON SHARED titleScene2 AS STRING
COMMON SHARED titleScene12 AS STRING
COMMON SHARED returnPreviousScene AS STRING

COMMON SHARED config_main AS STRING
COMMON SHARED filePrevious AS STRING
COMMON SHARED fileStat AS STRING

COMMON SHARED Exe_OK AS _BYTE
COMMON SHARED Exe_Fail AS _BYTE
COMMON SHARED Exe_Fail_First AS _BYTE
COMMON SHARED Exe_Fail_First_Stream1 AS _BYTE
COMMON SHARED Exe_Fail_First_Stream2 AS _BYTE

COMMON SHARED __MultiCameraSwitch AS _BYTE

'Tooltips
COMMON SHARED rtmp_codec_video_level$
COMMON SHARED rtmp_codec_video_profile$
COMMON SHARED rtmp_codec_audio_channels$
COMMON SHARED rtmp_codec_audio_samplerate$
COMMON SHARED rtmp_codec_audio_profile$
COMMON SHARED rtmp_codec_video_width$
COMMON SHARED rtmp_codec_video_height$
COMMON SHARED rtmp_codec_video_resolution$
COMMON SHARED rtmp_codec_version$
COMMON SHARED rtmp_codec_rtmp_version$

'Timer01
COMMON SHARED mouseX
COMMON SHARED mouseY
COMMON SHARED Timer_Fail AS INTEGER
COMMON SHARED Timer_Fail_Count AS INTEGER
COMMON SHARED Timer_Fail_Stream1 AS INTEGER
COMMON SHARED Timer_Fail_Stream2 AS INTEGER
COMMON SHARED FullScreen AS _BYTE
COMMON SHARED BG
COMMON SHARED nginx_warmup AS _BYTE
COMMON SHARED Port_Client$
COMMON SHARED td_update#
COMMON SHARED timer1#
COMMON SHARED Debug_Timer#
COMMON SHARED __returnPreviousScene
COMMON SHARED returnPreviousSceneTime AS _BYTE
COMMON SHARED returnFirstCheck
COMMON SHARED filePrevious
COMMON SHARED PUT_Refresh
COMMON SHARED NoKill
COMMON SHARED file96$
COMMON SHARED findSceneName
COMMON SHARED findSceneName2
COMMON SHARED streamsUp$
COMMON SHARED previousScene$
COMMON SHARED previousSceneDisplay$
COMMON SHARED rtmp_naccepted$
COMMON SHARED rtmp_bytes_in$
COMMON SHARED rtmp_bytes_out$
COMMON SHARED rtmp_bw_in$
COMMON SHARED rtmp_bw_out$
COMMON SHARED rtmp_codec_video$
COMMON SHARED rtmp_codec_audio$
COMMON SHARED rtmp_codec_nclients$
COMMON SHARED rtmp_codec_nclients#
COMMON SHARED rtmp_codec_nclients_temp#
COMMON SHARED a$
COMMON SHARED a2$
COMMON SHARED d$
COMMON SHARED I
COMMON SHARED i2
COMMON SHARED i3
COMMON SHARED stats_rtmp.xml$
COMMON SHARED tPing1#
COMMON SHARED client
COMMON SHARED tPing2#
COMMON SHARED tPingOut#
COMMON SHARED EOL$
COMMON SHARED Timer_GET!
COMMON SHARED __MultiCameraSwitch
COMMON SHARED Stream%
COMMON SHARED multiStream1#
COMMON SHARED multiStream2#
COMMON SHARED pos_xml_m&
COMMON SHARED Kb_Diff#
COMMON SHARED Bandwidth_Threshold
COMMON SHARED rtmp_bytes_in#
COMMON SHARED rtmp_bytes_in_temp1#
COMMON SHARED rtmp_bytes_in_temp2#
COMMON SHARED Stream_Fail_Delay
COMMON SHARED SD
COMMON SHARED Kb_Diff_stream1#
COMMON SHARED multiStream1_temp1#
COMMON SHARED multiStream1_temp2#
COMMON SHARED Kb_Diff_stream2#
COMMON SHARED multiStream2_temp1#
COMMON SHARED multiStream2_temp2#
COMMON SHARED Scene_OK
COMMON SHARED Scene_Fail
COMMON SHARED Scene_Intro
COMMON SHARED Exe_OK
COMMON SHARED Scene_Current$
COMMON SHARED Exe_Fail
COMMON SHARED lastStreamUp$
COMMON SHARED returnPreviousSceneRemember
COMMON SHARED titleScene1
COMMON SHARED titleScene2
COMMON SHARED titleScene12
COMMON SHARED OBS_URL
COMMON SHARED OBS_PW
COMMON SHARED Exe_Fail_First
COMMON SHARED Timer_Fail_First
COMMON SHARED Timer_Fail_First_Stream1
COMMON SHARED Exe_Fail_First_Stream1
COMMON SHARED Exe_Fail_First_Stream2
COMMON SHARED Timer_Fail_First_Stream
COMMON SHARED Timer_Fail_First_Stream2
COMMON SHARED td_display#

'Misc
COMMON SHARED FGwin AS LONG
COMMON SHARED file4_var AS STRING
COMMON SHARED file4_val AS STRING
COMMON SHARED BSOD AS LONG
COMMON SHARED OptionsMenuAlwaysOnTop AS INTEGER
COMMON SHARED AlwaysOnTop AS INTEGER
COMMON SHARED Myhwnd AS _UNSIGNED LONG
COMMON SHARED y AS LONG
COMMON SHARED HWND_TOPMOST AS LONG
COMMON SHARED SWP_NOMOVE AS LONG
COMMON SHARED SWP_NOSIZE AS LONG
COMMON SHARED SWP_SHOWWINDOW AS LONG
COMMON SHARED HWND_BOTTOM AS LONG
COMMON SHARED SWP_NOACTIVATE AS LONG
COMMON SHARED About AS INTEGER
COMMON SHARED Answer AS INTEGER
COMMON SHARED Pt AS LONG
COMMON SHARED x2 AS INTEGER
COMMON SHARED Px AS INTEGER
COMMON SHARED Py AS INTEGER
COMMON SHARED NULL AS INTEGER
COMMON SHARED xHeader1 AS STRING
COMMON SHARED xHeader2 AS STRING
COMMON SHARED xHeader3 AS STRING
COMMON SHARED xHeader4 AS STRING
COMMON SHARED xHeader5 AS STRING
COMMON SHARED xHeader6 AS STRING
COMMON SHARED xHeader7 AS STRING
COMMON SHARED xHeader8 AS STRING
COMMON SHARED xHeader9 AS STRING
COMMON SHARED x AS STRING
COMMON SHARED l AS INTEGER
COMMON SHARED rtmp_naccepted AS DOUBLE
COMMON SHARED rtmp_bytes_out AS DOUBLE
COMMON SHARED rtmp_bw_in AS DOUBLE
COMMON SHARED rtmp_bw_out AS DOUBLE

'OnLoad
COMMON SHARED config_main
COMMON SHARED URL
COMMON SHARED Port
COMMON SHARED fileStat
COMMON SHARED Desktop_Width_Position
COMMON SHARED Desktop_Height_Position
COMMON SHARED file4$
COMMON SHARED EqualFound
COMMON SHARED MultiCameraSwitch$
COMMON SHARED urlStream1
COMMON SHARED urlStream2
COMMON SHARED returnPreviousScene
COMMON SHARED returnPreviousSceneRemember$


'SUB Indicators
COMMON SHARED AliveIndicator!
COMMON SHARED __BGA
COMMON SHARED BGA
COMMON SHARED aioffsetX
COMMON SHARED aioffsetY

'SUB TIMEms
COMMON SHARED tout
COMMON SHARED tout#
COMMON SHARED tout2#
COMMON SHARED toutint#
COMMON SHARED toutdec#
COMMON SHARED plus

'SUB calcbw
COMMON SHARED bout
COMMON SHARED bout2#
COMMON SHARED bout#
COMMON SHARED boutnodec
COMMON SHARED bits
COMMON SHARED boutint#
COMMON SHARED boutm$
COMMON SHARED boutdec#
COMMON SHARED boutdec$

'FUNC calc_nginx$
COMMON SHARED convertTime#
COMMON SHARED includeSec
COMMON SHARED t_hr
COMMON SHARED t_min
COMMON SHARED t_sec

COMMON SHARED RED_WARNING AS _UNSIGNED LONG
COMMON SHARED RED_FAIL AS _UNSIGNED LONG
COMMON SHARED GREEN_OK AS _UNSIGNED LONG

RED_WARNING = _RGB32(205, 64, 32)
RED_FAIL = _RGB32(255, 32, 16)
GREEN_OK = _RGB32(123, 151, 163)

q = _EXIT

PUT_Fail:
IF ERR THEN CLS: _PRINTSTRING (20, 30), "ERR, _ERRORLINE:" + STR$(ERR) + "," + STR$(_ERRORLINE): _AUTODISPLAY: _DELAY 3: IF PUT_Refresh = 1 THEN PUT_Refresh = 0: Refresh_Request = 1: RESUME NEXT ELSE RESUME NEXT
